Multiple improvements
stevana/quickcheck-state-machine pull request #19
Opened 2023-05-16 14:02 UTC by jasagredo

This PR provides 4 improvements for QSM:
1. Boxes are now printed properly even if there is only a sequential prefix of actions, i.e.

```
┌────────────────────────────────────────────┐
│ [Var 0] ← Create                           │
│    → Created (Reference (Concrete Opaque)) │
└────────────────────────────────────────────┘
┌────────────────────────────────────────────┐
│ [] ← Write (Reference (Concrete Opaque)) 5 │
│                                  → Written │
└────────────────────────────────────────────┘
┌────────────────────────────────────────────┐
│ [] ← Read (Reference (Concrete Opaque))    │
│                              → ReadValue 6 │
└────────────────────────────────────────────┘

versus

┌┐
│ [Var 0] ← Create │
│ → Created (Reference (Concrete Opaque)) │
└┘
┌┐
│ [] ← Write (Reference (Concrete Opaque)) 5 │
│ → Written │
└┘
┌┐
│ [] ← Read (Reference (Concrete Opaque)) │
│ → ReadValue 6 │
└┘
```

2. Exceptions are printed outside of the boxed layout, i.e.

```
Tests
  MemoryReference
    CrashAndLogicBugParallel: 
┌──────────────────────────────────────────────────────────────────────────────────────────┐
│ [Var 0] ← Create                                                                         │
│                                                  → Created (Reference (Concrete Opaque)) │
└──────────────────────────────────────────────────────────────────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────────────────┐
│ [] ← Read (Reference (Concrete Opaque))                                                  │
│                                                                            → ReadValue 0 │
└──────────────────────────────────────────────────────────────────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────────────────┐
│ Create                                                                                   │
│                                                  → Created (Reference (Concrete Opaque)) │
└──────────────────────────────────────────────────────────────────────────────────────────┘
                                            │ ┌────────────────────────────────────────────┐
                                            │ │ [] ← Write (Reference (Concrete Opaque)) 0 │
┌─────────────────────────────────────────┐ │ │                                            │
│ [] ← Read (Reference (Concrete Opaque)) │ │ │                                            │
│                                         │ │ │                              → Exception 0 │
│                                         │ │ └────────────────────────────────────────────┘
│                           → ReadValue 1 │ │                                               
└─────────────────────────────────────────┘ │                                               
                                            │ │                                  → Written │
                                            │ └────────────────────────────────────────────┘

Exception 0:
  Crash after writing!
  CallStack (from HasCallStack):
    error, called at test/MemoryReference.hs:165:9 in main:MemoryReference

versus

Tests
  MemoryReference
    CrashAndLogicBugParallel: 
┌──────────────────────────────────────────────────────────────────────────────────────────┐
│ [Var 0] ← Create                                                                         │
│                                                  → Created (Reference (Concrete Opaque)) │
└──────────────────────────────────────────────────────────────────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────────────────┐
│ [] ← Read (Reference (Concrete Opaque))                                                  │
│                                                                            → ReadValue 0 │
└──────────────────────────────────────────────────────────────────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────────────────┐
│ Create                                                                                   │
│                                                  → Created (Reference (Concrete Opaque)) │
└──────────────────────────────────────────────────────────────────────────────────────────┘
                                            │ ┌────────────────────────────────────────────┐
                                            │ │ [] ← Write (Reference (Concrete Opaque)) 0 │
┌─────────────────────────────────────────┐ │ │                                            │
│ [] ← Read (Reference (Concrete Opaque)) │ │ │                                            │
│                                         │ │ │                              → CallStack (from HasCallStack):
    error, called at test/MemoryReference.hs:165:9 in main:MemoryReference │
│                                         │ │ └────────────────────────────────────────────┘
│                           → ReadValue 1 │ │                                               
└─────────────────────────────────────────┘ │                                               
                                            │ │                                  → Written │
                                            │ └────────────────────────────────────────────┘
```

3. There is a suggestion that the cause might be a logic bug or a race condition (see bottom of next example)
4. A new parameter is provided for the semantics to produce output for each test-case run, so that it can be seen at the counterexample:

```
Tests
  TicketDispenser
    ParallelWithSharedLock: 
┌──────────────────────────────────┐
│ [] ← Reset                       │
│                        → ResetOk │
└──────────────────────────────────┘
               │ ┌─────────────────┐
               │ │ [] ← TakeTicket │
┌────────────┐ │ │                 │
│ [] ← Reset │ │ │                 │
│            │ │ │   → GotTicket 0 │
│            │ │ └─────────────────┘
│  → ResetOk │ │                    
└────────────┘ │                    

EitherC (PredicateC (Just 0 :/= Just 1)) (PredicateC (Just 0 :/= Just 1))

The execution emitted the following trace messages:
  [RESET] Locking
  [RESET] Reset done
  [RESET] Freed
  [PID 1] [RESET] Locking
  [PID 2] [TAKE]  Locking
  [PID 2] [TAKE]  Last ticket was -1
  [PID 2] [TAKE]  Freed, got ticket 0
  [PID 1] [RESET] Reset done
  [PID 1] [RESET] Freed

However, some repetitions of this sequence of commands passed. Maybe there is a race condition?
```

I could try to split these improvements in separate steps, or we can merge all of them at once.

2023-05-22 13:10 UTC, stevana requested changes
Left a couple of comments about things that I didn't understand.

(Breaking it up in multiple PRs would probably have made it easier to review and merge.)

2023-05-22 13:10 UTC, stevana commented on test/Bookstore.hs
> +  Nothing generator shrinker (semantics bug) mock noCleanup Nothing
Doesn't the type of `semantics` need to change need to change to have `Tracer` in this and all other tests (except ticket dispenser and ioref)?

2023-05-30 07:50 UTC, jasagredo commented
@stevana I made a separate PR (#21) which includes the (I think) uncontroversial changes. 

I left out the tracing changes on purpose. To me it feels natural that monadic state machines emit traces and QSM could support them, but it is true that the user can add them on their own.

2023-05-30 13:37 UTC, stevana commented
> To me it feels natural that monadic state machines emit traces and QSM could support them, but it is true that the user can add them on their own.

We already emit traces in terms of [`History`](https://github.com/stevana/quickcheck-state-machine/blob/master/src/Test/StateMachine/Types/History.hs) perhaps that can also be used to do what you need?

2023-06-01 11:39 UTC, closed without merging